export type Line={id:string;number:string;name:string;color:string;textColor:string;order:number};
export type Station={id:string;nameBg:string;nameLat:string;slug:string;lines:string[];x:number;y:number;terminal?:boolean;features:string[];mapUrl:string};
export type Segment={id:string;from:string;to:string;line:string;minutes:number;estimated:true;closed?:boolean};
export type RouteStep={type:'ride'|'transfer';from:string;to:string;line:string;minutes:number;segmentId?:string;transferId?:string;stageId?:string;label?:string;count?:number};
const lines:Line[]=[{id:'m1',number:'1',name:'Сливница — Бизнес парк',color:'#e4252c',textColor:'#fff',order:1},{id:'m2',number:'2',name:'Обеля — Витоша',color:'#1677b8',textColor:'#fff',order:2},{id:'m3',number:'3',name:'Хаджи Димитър — Горна баня',color:'#168f62',textColor:'#fff',order:3},{id:'m4',number:'4',name:'Обеля — Летище София',color:'#e8ad18',textColor:'#17242b',order:4}];
const defs:Record<string,[string,string,number,number,string?]>={
obelya:['Обеля','Obelya',110,170,'rail park'],slivnitsa:['Сливница','Slivnitsa',90,300],lyulin:['Люлин','Lyulin',145,330],zapaden_park:['Западен парк','Zapaden Park',200,360],vardar:['Вардар','Vardar',255,390],konstantin_velichkov:['Константин Величков','Konstantin Velichkov',310,420],opalchenska:['Опълченска','Opalchenska',365,450],serdika:['Сердика','Serdika',440,450],su_kliment:['СУ Св. Климент Охридски','SU St. Kliment Ohridski',535,410],stadion_vasil_levski:['Стадион Васил Левски','Vasil Levski Stadium',590,445],joliot_curie:['Жолио Кюри','Joliot-Curie',645,480],gm_dimitrov:['Г. М. Димитров','G. M. Dimitrov',700,515],musagenitsa:['Мусагеница','Musagenitsa',755,550],mladost_1:['Младост 1','Mladost 1',810,585],mladost_3:['Младост 3','Mladost 3',860,610],aleksandar_malinov:['Александър Малинов','Aleksandar Malinov',900,640],akad_balan:['Акад. Ал. Теодоров – Балан','Akad. Al. Teodorov–Balan',945,665],business_park:['Бизнес парк','Business Park',1000,690,'park'],
lomsko_shose:['Ломско шосе','Lomsko Shose',160,195],beli_dunav:['Бели Дунав','Beli Dunav',215,220],nadezhda:['Надежда','Nadezhda',270,245],han_kubrat:['Хан Кубрат','Han Kubrat',325,270],maria_luiza:['Княгиня Мария Луиза','Knyaginya Maria Luiza',380,295],central_station:['Централна жп гара','Central Railway Station',420,325,'rail bus'],lavov_most:['Лъвов мост','Lavov Most',435,375],serdika_2:['Сердика II','Serdika II',455,470],ndk_2:['НДК II','NDK II',485,520],evropeyski_sayuz:['Европейски съюз','European Union',510,565],james_bourchier:['Джеймс Баучер','James Bourchier',540,615],vitosha:['Витоша','Vitosha',570,665,'park'],
hadzhi_dimitar:['Хаджи Димитър','Hadzhi Dimitar',630,190],teatralna:['Театрална','Teatralna',600,245],orlov_most:['Орлов мост','Orlov Most',555,365],patriarh_evtimiy:['Патриарх Евтимий','Patriarh Evtimiy',525,455],ndk_3:['НДК','NDK',505,505],medicinski:['Медицински университет','Medical University',470,555],bulgaria:['България','Bulgaria',430,590],krasno_selo:['Красно село','Krasno Selo',385,620],tsar_boris:['Цар Борис III / Красно село','Tsar Boris III / Krasno Selo',340,645],ovcha_kupel:['Овча купел','Ovcha Kupel',295,665],miziya_nbu:['Мизия / НБУ','Moesia / NBU',245,680],ovcha_kupel_2:['Овча купел II','Ovcha Kupel II',190,690],gorna_banya:['Горна баня','Gorna Banya',130,700,'rail park'],georgi_asparuhov:['Стадион Георги Аспарухов','Georgi Asparuhov Stadium',675,145],besarabiya:['Бесарабия','Besarabia',720,110],vladimir_vazov:['Ген. Владимир Вазов','Gen. Vladimir Vazov',770,75],
sofia_airport:['Летище София','Sofia Airport',1000,120,'airport'],sofiyska_sveta_gora:['Софийска Света гора','Sofiyska Sveta Gora',950,155],iskarsko_shose:['Искърско шосе','Iskarsko Shose',900,190,'rail'],druzhba:['Дружба','Druzhba',865,230],inter_expo:['Интер Експо Център – Цариградско шосе','Inter Expo Center – Tsarigradsko Shose',840,280,'park']};
const seq:Record<string,string[]>={m1:['slivnitsa','lyulin','zapaden_park','vardar','konstantin_velichkov','opalchenska','serdika','su_kliment','stadion_vasil_levski','joliot_curie','gm_dimitrov','musagenitsa','mladost_1','mladost_3','aleksandar_malinov','akad_balan','business_park'],m2:['obelya','lomsko_shose','beli_dunav','nadezhda','han_kubrat','maria_luiza','central_station','lavov_most','serdika_2','ndk_2','evropeyski_sayuz','james_bourchier','vitosha'],m3:['vladimir_vazov','besarabiya','georgi_asparuhov','hadzhi_dimitar','teatralna','orlov_most','patriarh_evtimiy','ndk_3','medicinski','bulgaria','krasno_selo','tsar_boris','ovcha_kupel','miziya_nbu','ovcha_kupel_2','gorna_banya'],m4:['obelya','slivnitsa','lyulin','zapaden_park','vardar','konstantin_velichkov','opalchenska','serdika','su_kliment','mladost_1','mladost_3','inter_expo','druzhba','iskarsko_shose','sofiyska_sveta_gora','sofia_airport']};
const membership=new Map<string,string[]>();Object.entries(seq).forEach(([l,ids])=>ids.forEach(id=>membership.set(id,[...(membership.get(id)||[]),l])));
const labels:Record<string,string>={rail:'жп връзка',bus:'автогара',park:'Park & Ride',airport:'летище'};
const stations:Station[]=Object.entries(defs).map(([id,[nameBg,nameLat,x,y,flags]])=>({id,nameBg,nameLat,slug:id.replaceAll('_','-'),lines:membership.get(id)||[],x,y,terminal:Object.values(seq).some(s=>s[0]===id||s.at(-1)===id),features:(flags||'').split(' ').filter(Boolean).map(f=>labels[f]),mapUrl:`https://www.openstreetmap.org/search?query=${encodeURIComponent(nameBg+' metro Sofia')}`}));
const segments:Segment[]=[];Object.entries(seq).forEach(([line,ids])=>ids.slice(0,-1).forEach((from,i)=>segments.push({id:`ride-${line}-${from}-${ids[i+1]}`,from,to:ids[i+1],line,minutes:2,estimated:true,closed:line==='m4'&&from==='obelya'&&ids[i+1]==='slivnitsa'}))); 
const transfers=[{id:'transfer-serdika',from:'serdika',to:'serdika_2',minutes:4},{id:'transfer-ndk',from:'ndk_2',to:'ndk_3',minutes:4},{id:'transfer-su-orlov',from:'su_kliment',to:'orlov_most',minutes:5}];
const hubs=[{id:'hub-serdika',kind:'transfer',x1:440,y1:450,x2:455,y2:470,lines:['m1','m2']},{id:'hub-ndk',kind:'transfer',x1:485,y1:520,x2:505,y2:505,lines:['m2','m3']},{id:'hub-mladost-1',kind:'shared',x1:810,y1:577,x2:810,y2:593,lines:['m1','m4']}];
const byId=new Map(stations.map(s=>[s.id,s])),lineById=new Map(lines.map(l=>[l.id,l]));
function route(start:string,end:string){type N={id:string;steps:RouteStep[];cost:number;transfers:number};const q:N[]=[{id:start,steps:[],cost:0,transfers:0}],best=new Map<string,number>(),found:N[]=[];while(q.length&&found.length<3){q.sort((a,b)=>a.cost-b.cost);const n=q.shift()!,k=n.id+'|'+(n.steps.at(-1)?.line||'');if((best.get(k)??Infinity)<=n.cost)continue;best.set(k,n.cost);if(n.id===end){found.push(n);continue}for(const s of segments){if(s.closed)continue;let to='';if(s.from===n.id)to=s.to;else if(s.to===n.id)to=s.from;if(!to)continue;const last=n.steps.at(-1)?.line,penalty=last&&last!==s.line?5:0;q.push({id:to,cost:n.cost+s.minutes+penalty,transfers:n.transfers+(penalty?1:0),steps:[...n.steps,{type:'ride',from:n.id,to,line:s.line,minutes:s.minutes,segmentId:s.id}]})}for(const t of transfers){const to=t.from===n.id?t.to:t.to===n.id?t.from:'';if(to)q.push({id:to,cost:n.cost+t.minutes,transfers:n.transfers+1,steps:[...n.steps,{type:'transfer',from:n.id,to,line:n.steps.at(-1)?.line||'m1',minutes:t.minutes,transferId:t.id}]})}}return found.map((r,i)=>({id:`route-${i}-${start}-${end}`,steps:r.steps,minutes:r.cost+4,transfers:r.transfers,rides:r.steps.filter(s=>s.type==='ride').length}))}
function compact(steps:RouteStep[]){const out:RouteStep[]=[];for(const s of steps){const last=out.at(-1);if(s.type==='ride'&&last?.type==='ride'&&last.line===s.line){last.to=s.to;last.minutes+=s.minutes;last.count=(last.count||1)+1;last.label=`Линия ${s.line.slice(1)} до ${byId.get(s.to)?.nameBg}`;last.stageId=`stage-${out.length}`}else out.push({...s,count:s.type==='ride'?1:undefined,label:s.type==='ride'?`Линия ${s.line.slice(1)} до ${byId.get(s.to)?.nameBg}`:undefined,stageId:`stage-${out.length}`})}return out}
export const metro={lines,stations,segments,transfers,hubs,byId,lineById,route,compact};

