const path = require("path");
const express = require("express");

const searchRoutes = require("./routes/search");
const rubricRoutes = require("./routes/rubric");
const objectRoutes = require("./routes/object");
const coordRoutes = require("./routes/coord");
const routingRoutes = require("./routes/routing");
const isochroneRoutes = require("./routes/isochrone");
const pagesRoutes = require("./routes/pages");

// 2026-09-14 (Meilisearch migration, search-results-plan.md §12-§13): /api/search
// now relies ENTIRELY on Meilisearch — there is no more SQL fallback inside
// search.js. That means this process must not start ACCEPTING requests until
// (a) the Meilisearch server (started separately, see start-meilisearch.bat)
// is actually reachable, and (b) a fresh reindex of it off the current
// sofia.db has completed — otherwise the very first requests after a restart
// would hit empty/stale indexes. Both are awaited below, before app.listen.
const meili = require("./lib/meiliClient");
const { main: reindexMeilisearch } = require("./scripts/reindexMeilisearch");
const streetsDirectory = require("./lib/streetsDirectory");
const rubricsDirectory = require("./lib/rubricsDirectory");

const PORT = process.env.PORT || 5173;
const WEB_DIR = path.resolve(__dirname, "..", "..", "web");
const DATA_DIR = path.resolve(__dirname, "..", "..", "data");

const app = express();

// API (search, rubric browsing, object details, route stops, hit-test) —
// mirrors the /services/* endpoints from the moscowmap reference.
app.use("/api", searchRoutes);
app.use("/api", rubricRoutes);
app.use("/api", objectRoutes);
app.use("/api", coordRoutes);
// "Как доехать/как дойти" (claude/next-steps-routing.md) -- proxies to a
// separately-run Motis process (MOTIS_URL env var, defaults to
// http://127.0.0.1:8081) rather than calculating anything itself.
app.use("/api", routingRoutes);
// "Зона доступности" (claude/next-steps-walkability-isochrone.md) --
// proxies to a separately-run pyvalhalla-based process (VALHALLA_URL env
// var, defaults to http://127.0.0.1:8082), same satellite-process pattern
// as routingRoutes above.
app.use("/api", isochroneRoutes);

// Static, crawlable directory section — now including "/" itself as the
// site's landing/hub page (2026-09-07: "/" used to be the bare SPA below;
// the interactive map moved to "/map/" so the root URL can be real,
// indexable HTML that links into every section — see pages.js's own
// comment on the "/" route for the reasoning). Mounted before the SPA's
// static handler so its routes win.
app.use(pagesRoutes);

// Static frontend + PMTiles data. express.static supports HTTP Range
// requests out of the box, which is what pmtiles.js needs to read tiles
// directly out of a single static file (no tile server required).
//
// 2026-09-08: `/data` used to get `maxAge: "1h"` — a *plain* max-age, with
// no revalidation at all, so a browser that had already fetched e.g.
// data/overlay_stations.geojson would keep serving that exact byte-for-byte
// response from disk for up to an hour with ZERO request to the server,
// not even a conditional one. This is exactly the bug below (`/map`'s own
// no-cache header) was fixed for, except worse — "no-cache" still
// re-checks every load, while a fresh max-age doesn't check at all. Caught
// this round when a delivered fix (round 11's split station badges) was
// confirmed live in one browser tab but the user's own tab — which had
// loaded the map earlier, within that hour window — kept showing the old
// "Сердика" badge (plain color, no diagonal split) with a *matching*
// `line_split` value that direct inspection showed the server was already
// serving correctly: the JS was fresh (it has its own no-cache header,
// below), the GeoJSON it read was stale. data/*.geojson (overlay_stations,
// subway_lines, cityBoundary, ...) gets regenerated by the pipeline just as
// often as web/js/*.js during active development, so it needs the same
// no-cache treatment, not a separate/looser policy. Applies to the pmtiles
// files too now (previously the whole point of `maxAge: "1h"`) — no-cache
// still lets Range requests and disk caching work exactly as before, it
// just adds one cheap conditional round-trip before reusing a cached range.
app.use("/data", express.static(DATA_DIR, { setHeaders: (res) => res.set("Cache-Control", "no-cache") }));
// The web/js/*.js files get edited and redelivered often during active
// development (search/hover-click fixes, most recently 2026-09-06) — a
// plain `express.static(WEB_DIR)` sends no Cache-Control at all, and a
// user reported a fix not taking effect after a full server restart
// because the browser kept serving its own cached copy of map-search.js
// without ever re-checking with the server (no explicit header means the
// browser is free to apply its own heuristic caching, and evidently did).
// `Cache-Control: no-cache` still lets the browser keep a cached copy, but
// forces it to revalidate with the server (a cheap conditional request)
// before using it, so an edited file is picked up on the next normal page
// reload — no more relying on the user doing a hard-refresh.
//
// 2026-09-07: moved from "/" to "/map" — the interactive SPA (MapLibre +
// search) is now a sub-application under its own URL rather than the
// site's front door; "/" itself is served by pagesRoutes above as a real
// server-rendered landing page. web/index.html's own asset references
// (css/..., js/...) are relative, so they still resolve correctly under
// the new "/map/" mount without any change to that file's markup.
app.use("/map", express.static(WEB_DIR, { setHeaders: (res) => res.set("Cache-Control", "no-cache") }));

// Polls Meilisearch's /health endpoint until it responds or timeoutMs
// elapses. meilisearch.exe is started as its own process a few seconds
// before this one (see start-meilisearch.bat) but there's no guarantee it's
// finished loading its own on-disk index data by the time this process's
// first tick runs, especially on a cold boot right after the machine starts.
async function waitForMeiliHealth(timeoutMs = 30000, intervalMs = 500) {
  const deadline = Date.now() + timeoutMs;
  let lastErr = null;
  while (Date.now() < deadline) {
    try {
      await meili.health();
      return;
    } catch (err) {
      lastErr = err;
      await new Promise((r) => setTimeout(r, intervalMs));
    }
  }
  throw new Error(
    `Meilisearch did not become reachable within ${timeoutMs}ms (last error: ${lastErr && lastErr.message}). ` +
      "Is meilisearch.exe running? (see start-meilisearch.bat)"
  );
}

async function start() {
  const t0 = Date.now();
  console.log("[startup] waiting for Meilisearch to be reachable...");
  await waitForMeiliHealth();
  console.log(`[startup] Meilisearch reachable after ${Date.now() - t0}ms, reindexing...`);

  const t1 = Date.now();
  await reindexMeilisearch();
  console.log(`[startup] reindex complete in ${Date.now() - t1}ms`);

  // 2026-09-14 (§14, real-machine deployment finding): on the real Windows
  // machine, the FIRST search against a just-reindexed Meilisearch index
  // sometimes threw "Too many spurious wake ups while trying to open the
  // index X" (Windows file-locking/AV-scan contention while Meilisearch
  // lazily opens that index's memory-mapped files, right after reindex just
  // wrote them) — never seen in the Linux sandbox. Forcing one throwaway
  // search per index here, before app.listen, absorbs that one-time "first
  // open" cost/flakiness at startup instead of a live user's search request
  // hitting it. See routes/search.js's warmUpMeiliIndexes and
  // meiliSearchSub's retry comment for the full story.
  const t1b = Date.now();
  await searchRoutes.warmUpMeiliIndexes();
  console.log(`[startup] Meilisearch index warm-up: ${Date.now() - t1b}ms`);

  // 2026-09-14 (§12.5 perf fix, verification): streetsDirectory.get() and
  // rubricsDirectory.listRubrics() are lazy singletons — without forcing
  // them here, whichever live request happens to be first (after this
  // process starts) pays their one-time build cost (~0.4-1s for streets on
  // this dataset) instead of it being absorbed into server startup, where a
  // human isn't waiting on a specific response. Cheap and safe to force
  // eagerly (both are pure in-memory builds off the already-open, read-only
  // sofia.db — see either module's own top comment).
  const t2 = Date.now();
  streetsDirectory.get();
  rubricsDirectory.listRubrics();
  console.log(`[startup] directory warm-up: ${Date.now() - t2}ms`);

  app.listen(PORT, () => {
    console.log(`Sofia map server running at http://localhost:${PORT}`);
    console.log(`[startup] total startup time: ${Date.now() - t0}ms`);
  });
}

start().catch((err) => {
  console.error("[startup] FATAL — server did not start:", err);
  process.exit(1);
});
